# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='style',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='output',
            field=models.CharField(default='not provided', max_length=200),
        ),
    ]
