# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20170404_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='output',
            field=models.CharField(default='nothing', max_length=200),
        ),
    ]
